import { UserBasicInfo, EmployeeEducationInfo, EmployeeExperienceInfo, EmployeePersonalInfo } from "../employee";

export const dummyEmployeeBasicInfos: UserBasicInfo[] = [
    ({
        username: "alice",
        email: "alice@example.com",
        firstName: "Alice",
        lastName: "Smith",
        id: "2",
        isActive: true,
        lastLogin: new Date(),
        role: "supervisor",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "HR",
        designation: "HR Manager",
        phone: "2345678901",
        jobStatus: "Full-time",
        joiningDate: new Date(),

    }),
    ({
        username: "bob",
        email: "bob@example.com",
        firstName: "Bob",
        lastName: "Johnson",
        id: "3",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Backend Developer",
        phone: "3456789012",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "charlie",
        email: "charlie@example.com",
        firstName: "Charlie",
        lastName: "Brown",
        id: "4",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "Design",
        designation: "UI/UX Designer",
        phone: "4567890123",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "david",
        email: "david@example.com",
        firstName: "David",
        lastName: "Williams",
        id: "5",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Frontend Developer",
        phone: "5678901234",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "eve",
        email: "eve@example.com",
        firstName: "Eve",
        lastName: "Davis",
        id: "6",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Full Stack Developer",
        phone: "6789012345",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "frank",
        email: "frank@example.com",
        firstName: "Frank",
        lastName: "Miller",
        id: "7",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "DevOps Engineer",
        phone: "7890123456",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "grace",
        email: "grace@example.com",
        firstName: "Grace",
        lastName: "Wilson",
        id: "8",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Mobile Developer",
        phone: "8901234567",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "henry",
        email: "henry@example.com",
        firstName: "Henry",
        lastName: "Moore",
        id: "9",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Data Scientist",
        phone: "9012345678",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "irene",
        email: "irene@example.com",
        firstName: "Irene",
        lastName: "Taylor",
        id: "10",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Machine Learning Engineer",
        phone: "0123456789",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "jack",
        email: "jack@example.com",
        firstName: "Jack",
        lastName: "Anderson",
        id: "11",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Security Engineer",
        phone: "1234567890",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "karen",
        email: "karen@example.com",
        firstName: "Karen",
        lastName: "Thomas",
        id: "12",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Cloud Engineer",
        phone: "2345678901",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "leo",
        email: "leo@example.com",
        firstName: "Leo",
        lastName: "Jackson",
        id: "13",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Blockchain Developer",
        phone: "3456789012",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "mia",
        email: "mia@example.com",
        firstName: "Mia",
        lastName: "White",
        id: "14",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Game Developer",
        phone: "4567890123",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "nina",
        email: "nina@example.com",
        firstName: "Nina",
        lastName: "Harris",
        id: "15",
        isActive: true,
        lastLogin: new Date(),
        role: "HR",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Embedded Systems Engineer",
        phone: "5678901234",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "oliver",
        email: "oliver@example.com",
        firstName: "Oliver",
        lastName: "Martin",
        id: "16",
        isActive: true,
        lastLogin: new Date(),
        role: "system admin",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Systems Engineer",
        phone: "6789012345",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "paul",
        email: "paul@example.com",
        firstName: "Paul",
        lastName: "Garcia",
        id: "17",
        isActive: true,
        lastLogin: new Date(),
        role: "super admin",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Network Engineer",
        phone: "7890123456",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "quinn",
        email: "quinn@example.com",
        firstName: "Quinn",
        lastName: "Martinez",
        id: "18",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Site Reliability Engineer",
        phone: "8901234567",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "rachel",
        email: "rachel@example.com",
        firstName: "Rachel",
        lastName: "Robinson",
        id: "19",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Database Administrator",
        phone: "9012345678",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "sam",
        email: "sam@example.com",
        firstName: "Sam",
        lastName: "Clark",
        id: "20",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Software Tester",
        phone: "0123456789",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
];

export const dummyEmployeePersonalInfos: EmployeePersonalInfo[] = [
    {
        gender: 'Female',
        fatherName: 'Robert Smith',
        dateOfBirth: new Date('1985-05-15'),
        motherName: 'Emily Smith',
        religion: 'Christianity',
        spouseName: 'John Doe',
        bloodGroup: 'A+',
        emergencyContact: '2345678901',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1'],
        phoneEC: '1234567890',
        nidNumber: 234567890,
        address: '456 Elm St, Anytown, USA'
    },
    {
        gender: 'Male',
        fatherName: 'Michael Johnson',
        dateOfBirth: new Date('1978-03-22'),
        motherName: 'Sarah Johnson',
        religion: 'Christianity',
        spouseName: 'Anna Johnson',
        bloodGroup: 'B+',
        emergencyContact: '3456789012',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1', 'Child2', 'Child3'],
        phoneEC: '2345678901',
        nidNumber: 345678901,
        address: '789 Pine St, Anytown, USA'
    },
    {
        gender: 'Female',
        fatherName: 'William Brown',
        dateOfBirth: new Date('1992-07-30'),
        motherName: 'Linda Brown',
        religion: 'Christianity',
        spouseName: 'David Brown',
        bloodGroup: 'AB+',
        emergencyContact: '4567890123',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1'],
        phoneEC: '3456789012',
        nidNumber: 456789012,
        address: '101 Maple St, Anytown, USA'
    },
    {
        gender: 'Male',
        fatherName: 'James Williams',
        dateOfBirth: new Date('1980-11-11'),
        motherName: 'Patricia Williams',
        religion: 'Christianity',
        spouseName: 'Laura Williams',
        bloodGroup: 'O-',
        emergencyContact: '5678901234',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1', 'Child2'],
        phoneEC: '4567890123',
        nidNumber: 567890123,
        address: '202 Oak St, Anytown, USA'
    },
    {
        gender: 'Female',
        fatherName: 'Charles Davis',
        dateOfBirth: new Date('1988-09-09'),
        motherName: 'Barbara Davis',
        religion: 'Christianity',
        spouseName: 'James Davis',
        bloodGroup: 'A-',
        emergencyContact: '6789012345',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1'],
        phoneEC: '5678901234',
        nidNumber: 678901234,
        address: '303 Birch St, Anytown, USA'
    },
    {
        gender: 'Male',
        fatherName: 'Joseph Miller',
        dateOfBirth: new Date('1975-12-25'),
        motherName: 'Nancy Miller',
        religion: 'Christianity',
        spouseName: 'Karen Miller',
        bloodGroup: 'B-',
        emergencyContact: '7890123456',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1', 'Child2', 'Child3'],
        phoneEC: '6789012345',
        nidNumber: 789012345,
        address: '404 Cedar St, Anytown, USA'
    },
    {
        gender: 'Female',
        fatherName: 'Thomas Wilson',
        dateOfBirth: new Date('1995-02-14'),
        motherName: 'Betty Wilson',
        religion: 'Christianity',
        spouseName: 'Michael Wilson',
        bloodGroup: 'AB-',
        emergencyContact: '8901234567',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1'],
        phoneEC: '7890123456',
        nidNumber: 890123456,
        address: '505 Spruce St, Anytown, USA'
    },
    {
        gender: 'Male',
        fatherName: 'Christopher Moore',
        dateOfBirth: new Date('1983-04-18'),
        motherName: 'Sandra Moore',
        religion: 'Christianity',
        spouseName: 'Jessica Moore',
        bloodGroup: 'O+',
        emergencyContact: '9012345678',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1', 'Child2'],
        phoneEC: '8901234567',
        nidNumber: 901234567,
        address: '606 Walnut St, Anytown, USA'
    },
    {
        gender: 'Female',
        fatherName: 'Daniel Taylor',
        dateOfBirth: new Date('1987-06-06'),
        motherName: 'Donna Taylor',
        religion: 'Christianity',
        spouseName: 'Brian Taylor',
        bloodGroup: 'A+',
        emergencyContact: '0123456789',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1'],
        phoneEC: '9012345678',
        nidNumber: 123456789,
        address: '707 Chestnut St, Anytown, USA'
    },
    {
        gender: 'Male',
        fatherName: 'Matthew Anderson',
        dateOfBirth: new Date('1979-08-08'),
        motherName: 'Carol Anderson',
        religion: 'Christianity',
        spouseName: 'Rebecca Anderson',
        bloodGroup: 'B+',
        emergencyContact: '1234567890',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1', 'Child2', 'Child3'],
        phoneEC: '0123456789',
        nidNumber: 234567890,
        address: '808 Willow St, Anytown, USA'
    },
    {
        gender: 'Female',
        fatherName: 'Anthony Thomas',
        dateOfBirth: new Date('1991-10-10'),
        motherName: 'Sharon Thomas',
        religion: 'Christianity',
        spouseName: 'Steven Thomas',
        bloodGroup: 'AB+',
        emergencyContact: '2345678901',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1'],
        phoneEC: '1234567890',
        nidNumber: 345678901,
        address: '909 Ash St, Anytown, USA'
    },
    {
        gender: 'Male',
        fatherName: 'Mark Jackson',
        dateOfBirth: new Date('1982-01-01'),
        motherName: 'Deborah Jackson',
        religion: 'Christianity',
        spouseName: 'Michelle Jackson',
        bloodGroup: 'O-',
        emergencyContact: '3456789012',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1', 'Child2'],
        phoneEC: '2345678901',
        nidNumber: 456789012,
        address: '1010 Poplar St, Anytown, USA'
    },
    {
        gender: 'Female',
        fatherName: 'Paul White',
        dateOfBirth: new Date('1986-03-03'),
        motherName: 'Cynthia White',
        religion: 'Christianity',
        spouseName: 'Kevin White',
        bloodGroup: 'A-',
        emergencyContact: '4567890123',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1'],
        phoneEC: '3456789012',
        nidNumber: 567890123,
        address: '1111 Fir St, Anytown, USA'
    },
    {
        gender: 'Male',
        fatherName: 'Steven Harris',
        dateOfBirth: new Date('1977-05-05'),
        motherName: 'Kathleen Harris',
        religion: 'Christianity',
        spouseName: 'Laura Harris',
        bloodGroup: 'B-',
        emergencyContact: '5678901234',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1', 'Child2', 'Child3'],
        phoneEC: '4567890123',
        nidNumber: 678901234,
        address: '1212 Maple St, Anytown, USA'
    },
    {
        gender: 'Female',
        fatherName: 'Edward Martin',
        dateOfBirth: new Date('1993-07-07'),
        motherName: 'Rebecca Martin',
        religion: 'Christianity',
        spouseName: 'James Martin',
        bloodGroup: 'AB-',
        emergencyContact: '6789012345',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1'],
        phoneEC: '5678901234',
        nidNumber: 789012345,
        address: '1313 Birch St, Anytown, USA'
    },
    {
        gender: 'Male',
        fatherName: 'George Garcia',
        dateOfBirth: new Date('1981-09-09'),
        motherName: 'Janet Garcia',
        religion: 'Christianity',
        spouseName: 'Susan Garcia',
        bloodGroup: 'O+',
        emergencyContact: '7890123456',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1', 'Child2'],
        phoneEC: '6789012345',
        nidNumber: 890123456,
        address: '1414 Cedar St, Anytown, USA'
    },
    {
        gender: 'Female',
        fatherName: 'Kenneth Martinez',
        dateOfBirth: new Date('1984-11-11'),
        motherName: 'Pamela Martinez',
        religion: 'Christianity',
        spouseName: 'David Martinez',
        bloodGroup: 'A+',
        emergencyContact: '8901234567',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1'],
        phoneEC: '7890123456',
        nidNumber: 901234567,
        address: '1515 Spruce St, Anytown, USA'
    },
    {
        gender: 'Male',
        fatherName: 'Brian Robinson',
        dateOfBirth: new Date('1976-02-02'),
        motherName: 'Carol Robinson',
        religion: 'Christianity',
        spouseName: 'Jennifer Robinson',
        bloodGroup: 'B+',
        emergencyContact: '9012345678',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1', 'Child2', 'Child3'],
        phoneEC: '8901234567',
        nidNumber: 123456789,
        address: '1616 Oak St, Anytown, USA'
    },
    {
        gender: 'Female',
        fatherName: 'Ronald Clark',
        dateOfBirth: new Date('1994-04-04'),
        motherName: 'Margaret Clark',
        religion: 'Christianity',
        spouseName: 'Charles Clark',
        bloodGroup: 'AB+',
        emergencyContact: '0123456789',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1'],
        phoneEC: '9012345678',
        nidNumber: 234567890,
        address: '1717 Willow St, Anytown, USA'
    },
    {
        gender: 'Male',
        fatherName: 'Kevin Lewis',
        dateOfBirth: new Date('1989-06-06'),
        motherName: 'Diane Lewis',
        religion: 'Christianity',
        spouseName: 'Angela Lewis',
        bloodGroup: 'O-',
        emergencyContact: '1234567890',
        maritalStatus: 'Married',
        relationWithEC: 'Spouse',
        children: ['Child1', 'Child2'],
        phoneEC: '0123456789',
        nidNumber: 345678901,
        address: '1818 Poplar St, Anytown, USA'
    }
];

export const dummyEmployeeEducationInfo: EmployeeEducationInfo = {
    degree: 'B.Sc. in Computer Science',
    institution: 'XYZ University',
    from: new Date('2015-01-01'),
    to: new Date('2019-01-01'),
    result: '3.8'
};

export const dummyEmployeeExperience: EmployeeExperienceInfo = {
    companyName: "Tech Solutions Inc.",
    designation: "Software Engineer",
    description: "Worked on developing and maintaining web applications.",
    from: new Date('2018-01-01'),
    to: new Date('2021-12-31')
};