import { Employee } from "../employee";

export const dummyEmployees: Employee[] = [
    ({
        username: "alice",
        email: "alice@example.com",
        firstName: "Alice",
        lastName: "Smith",
        id: "2",
        isActive: true,
        lastLogin: new Date(),
        role: "supervisor",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "HR",
        designation: "HR Manager",
        phone: "2345678901",
        jobStatus: "Full-time",
        joiningDate: new Date(),

    }),
    ({
        username: "bob",
        email: "bob@example.com",
        firstName: "Bob",
        lastName: "Johnson",
        id: "3",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Backend Developer",
        phone: "3456789012",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "charlie",
        email: "charlie@example.com",
        firstName: "Charlie",
        lastName: "Brown",
        id: "4",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "Design",
        designation: "UI/UX Designer",
        phone: "4567890123",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "david",
        email: "david@example.com",
        firstName: "David",
        lastName: "Williams",
        id: "5",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Frontend Developer",
        phone: "5678901234",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "eve",
        email: "eve@example.com",
        firstName: "Eve",
        lastName: "Davis",
        id: "6",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Full Stack Developer",
        phone: "6789012345",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "frank",
        email: "frank@example.com",
        firstName: "Frank",
        lastName: "Miller",
        id: "7",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "DevOps Engineer",
        phone: "7890123456",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "grace",
        email: "grace@example.com",
        firstName: "Grace",
        lastName: "Wilson",
        id: "8",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Mobile Developer",
        phone: "8901234567",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "henry",
        email: "henry@example.com",
        firstName: "Henry",
        lastName: "Moore",
        id: "9",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Data Scientist",
        phone: "9012345678",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "irene",
        email: "irene@example.com",
        firstName: "Irene",
        lastName: "Taylor",
        id: "10",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Machine Learning Engineer",
        phone: "0123456789",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "jack",
        email: "jack@example.com",
        firstName: "Jack",
        lastName: "Anderson",
        id: "11",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Security Engineer",
        phone: "1234567890",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "karen",
        email: "karen@example.com",
        firstName: "Karen",
        lastName: "Thomas",
        id: "12",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Cloud Engineer",
        phone: "2345678901",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "leo",
        email: "leo@example.com",
        firstName: "Leo",
        lastName: "Jackson",
        id: "13",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Blockchain Developer",
        phone: "3456789012",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "mia",
        email: "mia@example.com",
        firstName: "Mia",
        lastName: "White",
        id: "14",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Game Developer",
        phone: "4567890123",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "nina",
        email: "nina@example.com",
        firstName: "Nina",
        lastName: "Harris",
        id: "15",
        isActive: true,
        lastLogin: new Date(),
        role: "HR",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Embedded Systems Engineer",
        phone: "5678901234",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "oliver",
        email: "oliver@example.com",
        firstName: "Oliver",
        lastName: "Martin",
        id: "16",
        isActive: true,
        lastLogin: new Date(),
        role: "system admin",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Systems Engineer",
        phone: "6789012345",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "paul",
        email: "paul@example.com",
        firstName: "Paul",
        lastName: "Garcia",
        id: "17",
        isActive: true,
        lastLogin: new Date(),
        role: "super admin",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Network Engineer",
        phone: "7890123456",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "quinn",
        email: "quinn@example.com",
        firstName: "Quinn",
        lastName: "Martinez",
        id: "18",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Site Reliability Engineer",
        phone: "8901234567",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "rachel",
        email: "rachel@example.com",
        firstName: "Rachel",
        lastName: "Robinson",
        id: "19",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Bob Johnson",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Database Administrator",
        phone: "9012345678",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
    ({
        username: "sam",
        email: "sam@example.com",
        firstName: "Sam",
        lastName: "Clark",
        id: "20",
        isActive: true,
        lastLogin: new Date(),
        role: "end user",
        subordinates: [],
        supervisorName: "Alice Smith",
        companyName: "Acme Inc.",
        department: "IT",
        designation: "Software Tester",
        phone: "0123456789",
        jobStatus: "Full-time",
        joiningDate: new Date(),
    }),
];
