-- Seed data for countries and industries tables
-- These are reference tables required for company configuration
-- This script is idempotent and can be run multiple times safely

-- Populate Countries (ON CONFLICT will skip existing entries)
INSERT INTO countries (name) VALUES
  ('Afghanistan'),
  ('Albania'),
  ('Algeria'),
  ('Argentina'),
  ('Australia'),
  ('Austria'),
  ('Bangladesh'),
  ('Belgium'),
  ('Bhutan'),
  ('Brazil'),
  ('Canada'),
  ('China'),
  ('Denmark'),
  ('Egypt'),
  ('Finland'),
  ('France'),
  ('Germany'),
  ('Greece'),
  ('Hong Kong'),
  ('India'),
  ('Indonesia'),
  ('Iran'),
  ('Iraq'),
  ('Ireland'),
  ('Israel'),
  ('Italy'),
  ('Japan'),
  ('Jordan'),
  ('Kenya'),
  ('Kuwait'),
  ('Malaysia'),
  ('Maldives'),
  ('Mexico'),
  ('Nepal'),
  ('Netherlands'),
  ('New Zealand'),
  ('Nigeria'),
  ('Norway'),
  ('Oman'),
  ('Pakistan'),
  ('Philippines'),
  ('Poland'),
  ('Portugal'),
  ('Qatar'),
  ('Russia'),
  ('Saudi Arabia'),
  ('Singapore'),
  ('South Africa'),
  ('South Korea'),
  ('Spain'),
  ('Sri Lanka'),
  ('Sweden'),
  ('Switzerland'),
  ('Taiwan'),
  ('Thailand'),
  ('Turkey'),
  ('United Arab Emirates'),
  ('United Kingdom'),
  ('United States'),
  ('Vietnam')
ON CONFLICT (name) DO NOTHING;

-- Populate Industries (ON CONFLICT will skip existing entries)
INSERT INTO industries (name) VALUES
  ('Agriculture & Farming'),
  ('Automotive'),
  ('Banking & Finance'),
  ('Consulting'),
  ('Construction'),
  ('Education'),
  ('Energy & Utilities'),
  ('Entertainment & Media'),
  ('Food & Beverage'),
  ('Government & Public Sector'),
  ('Healthcare'),
  ('Hospitality & Tourism'),
  ('Information Technology'),
  ('Insurance'),
  ('Legal Services'),
  ('Logistics & Transportation'),
  ('Manufacturing'),
  ('Mining & Metals'),
  ('Non-Profit & NGO'),
  ('Oil & Gas'),
  ('Pharmaceuticals'),
  ('Real Estate'),
  ('Retail & E-commerce'),
  ('Telecommunications'),
  ('Textiles & Apparel'),
  ('Other')
ON CONFLICT (name) DO NOTHING;

-- Verify the data was inserted
SELECT 'Countries inserted:' as info, COUNT(*) as count FROM countries;
SELECT 'Industries inserted:' as info, COUNT(*) as count FROM industries;
